//==============================================================================
// Filename: AuditoryNoiseSettings.jsx
// Author: Aaron Thompson
// Date Created: 5/18/2026
// Last Updated: 5/18/2026
//
// Description: Stores lables, titles, and descriptions for noise types.
//==============================================================================
// VARIABLE(s)
//------------------------------------------------------------------------------
export const noiseTypes = [
    { label: 'White', description: { title: 'White Noise', description: 'Equal energy at every frequency. Power spectral density is flat across the entire spectrum. Generated by sampling independent Gaussian random variables.' } },
    { label: 'Pink', description: { title: 'Pink Noise', description: 'Power spectral density falls as 1/f — each octave carries equal energy. Ubiquitous in nature: heartbeats, river flows, electronic components.' } },
    { label: 'Brown', description: { title: 'Brown Noise', description: 'Power spectral density falls as 1/f² — equivalent to integrating white noise. Resembles a random walk. Deep, rumbling character with strong low frequency content.' } },
    { label: 'Blue', description: { title: 'Blue Noise', description: 'Power spectral density rises linearly with frequency — the spectral complement of pink noise. Higher frequencies dominate, producing a bright, hiss-like character.' } }
];
//==============================================================================
//==============================================================================